version: '3.9'
services:
  frontend:
    image: node:18.3
    user: "$USER_ID:$GROUP_ID"
    volumes: [".:/app:cached"]
    working_dir: /app/frontend/
    command: ["yarn", "run", "dev"]
    ports: ["3000:3000"]

  backend:
    image: rust:1.61
    volumes: [".:/app:cached"]
    working_dir: /app/backend/
    command: ["cargo", "run"]
    ports: ["8000:8000"]
    tty: true
    environment:
      HOST: "0.0.0.0:8000"
      RUST_LOG: "debug"

  nginx:
    image: nginx:1.16
    depends_on: [frontend, backend]
    volumes:
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/certificates/server.pem:/etc/ssl/server.pem:ro"
      - "./docker/certificates/server.key:/etc/ssl/server.key:ro"
    ports: ["80:80", "443:443"]
