version: '3.9'
services:
  frontend:
    image: node:19.3
    user: "$USER_ID:$GROUP_ID"
    volumes:
      - "./frontend:/app"
    working_dir: /app
    command: [ "yarn", "run", "dev", "--host" ]
    ports: [ "127.0.0.1:3000:3000" ]

  backend:
    image: rust:1.66
    depends_on: [ redis ]
    volumes:
      - ".:/app"
    working_dir: /app
    command: [ "cargo", "run", "--bin", "backend" ]
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      REDIS_URL: "redis://redis/"
      RUST_LOG: "backend=trace,warn"
    ports: [ "127.0.0.1:8000:8000" ]

  redis:
    image: redis:7.0
    ports: [ "127.0.0.1:6379:6379" ]

  nginx:
    image: nginx:1.23
    depends_on: [ frontend, backend ]
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports: [ "127.0.0.1:80:80" ]
